name: CI linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Make
      run: cd linux && make
    - name: Test
      run: cd linux && make test
